

[evolution]
entity_child_count = 1
entity_start_count = 100
grid_width = 100
grid_height = 100
neuron_connection_count = 4
neuron_fire_threshold = 0.0
neuron_signal_range = 4.0
render_pixel_scale = 8
sim_generation_steps = 100

[rock_paper_scissors]
grid_width = 200
grid_height = 200
render_pixel_scale = 4
